Fix bug where user can login to game twice
qerdcv/ttt-online pull request #29
Opened 2022-06-21 14:24 UTC by Drozd0f

2022-06-21 17:03 UTC, qerdcv requested changes

2022-06-21 17:03 UTC, qerdcv commented on src/handlers.py
> +        return web.json_response({'message': 'user already exist in game'}, status=404)
status 404?

2022-06-21 17:03 UTC, qerdcv commented on src/handlers.py
> +        return web.json_response({'message': 'user already exist in game'}, status=404)
And weird check.

If owner is in request => throw error that user is already logged in game, that's ok, but if another user tries to make few request to login, what will happen?

2022-06-21 17:43 UTC, Drozd0f commented on src/handlers.py
> +        return web.json_response({'message': 'user already exist in game'}, status=404)
status 400?

2022-06-21 17:43 UTC, Drozd0f commented on src/handlers.py
> +        return web.json_response({'message': 'user already exist in game'}, status=404)
"another user tries to make few request to login, what will happen" how i can emulate this?

2022-06-21 17:59 UTC, qerdcv commented on src/handlers.py
> +        return web.json_response({'message': 'user already exist in game'}, status=404)
Login as non-owner, and make requests login requests

2022-06-21 18:00 UTC, qerdcv commented on src/handlers.py
> +        return web.json_response({'message': 'user already exist in game'}, status=404)
Status conflict, user already in game

2022-06-22 11:15 UTC, qerdcv approved these changes

2022-06-22 11:56 UTC, merged